name: tp-tacs
services:
  tacs-backend:
    build: 
      context: ./
    ports:
      - 8080:8080

  tacs-frontend:
    build:
      context: ./front
    ports:
      - 3000:3000

  mongo:
    container_name: mongodb
    ports:
      - 27017:27017
    image: mongo
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: